export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_SURVEY_REQUEST = 'USER_SURVEY_REQUEST'
export const USER_SURVEY_SUCCESS = 'USER_SURVEY_SUCCESS'
export const USER_SURVEY_FAIL = 'USER_SURVEY_FAIL'



export const SURVEY_LIST_REQUEST = 'SURVEY_LIST_REQUEST'
export const SURVEY_LIST_SUCCESS = 'SURVEY_LIST_SUCCESS'
export const SURVEY_LIST_FAIL = 'SURVEY_LIST_FAIL'
export const SURVEY_LIST_RESET = 'SURVEY_LIST_RESET'